-- MySQL Script generated by MySQL Workbench
-- 10/14/20 05:36:35
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_bodeguitadeoro
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_bodeguitadeoro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_bodeguitadeoro` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `db_bodeguitadeoro` ;

-- -----------------------------------------------------
-- Table `db_bodeguitadeoro`.`tb_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_bodeguitadeoro`.`tb_categoria` (
  `idtb_categoria` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idtb_categoria`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_bodeguitadeoro`.`tb_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_bodeguitadeoro`.`tb_producto` (
  `idtb_producto` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `stock` DOUBLE NULL COMMENT '',
  `precio` INT NULL COMMENT '',
  `idtb_categoria` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idtb_producto`)  COMMENT '',
  INDEX `fk_tb_producto_tb_categoria_idx` (`idtb_categoria` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_producto_tb_categoria`
    FOREIGN KEY (`idtb_categoria`)
    REFERENCES `db_bodeguitadeoro`.`tb_categoria` (`idtb_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_bodeguitadeoro`.`tb_tipo_persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_bodeguitadeoro`.`tb_tipo_persona` (
  `idtb_tipo_persona` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idtb_tipo_persona`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_bodeguitadeoro`.`tb_persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_bodeguitadeoro`.`tb_persona` (
  `idtb_persona` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `apellido` VARCHAR(45) NULL COMMENT '',
  `correo` VARCHAR(45) NULL COMMENT '',
  `clave` VARCHAR(45) NULL COMMENT '',
  `idtb_tipo_persona` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idtb_persona`)  COMMENT '',
  INDEX `fk_tb_persona_tb_tipo_persona1_idx` (`idtb_tipo_persona` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_persona_tb_tipo_persona1`
    FOREIGN KEY (`idtb_tipo_persona`)
    REFERENCES `db_bodeguitadeoro`.`tb_tipo_persona` (`idtb_tipo_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_bodeguitadeoro`.`tb_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_bodeguitadeoro`.`tb_cliente` (
  `idtb_cliente` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `celular` VARCHAR(45) NULL COMMENT '',
  `direccion` VARCHAR(45) NULL COMMENT '',
  `referencia` VARCHAR(45) NULL COMMENT '',
  `idtb_persona` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idtb_cliente`)  COMMENT '',
  INDEX `fk_tb_cliente_tb_persona1_idx` (`idtb_persona` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_cliente_tb_persona1`
    FOREIGN KEY (`idtb_persona`)
    REFERENCES `db_bodeguitadeoro`.`tb_persona` (`idtb_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_bodeguitadeoro`.`tb_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_bodeguitadeoro`.`tb_pedido` (
  `idtb_pedido` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `fecha` DATETIME NULL COMMENT '',
  `monto` DOUBLE NULL COMMENT '',
  `idtb_cliente` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idtb_pedido`)  COMMENT '',
  INDEX `fk_tb_pedido_tb_cliente1_idx` (`idtb_cliente` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_pedido_tb_cliente1`
    FOREIGN KEY (`idtb_cliente`)
    REFERENCES `db_bodeguitadeoro`.`tb_cliente` (`idtb_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_bodeguitadeoro`.`tb_detalle_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_bodeguitadeoro`.`tb_detalle_pedido` (
  `idtb_producto` INT NOT NULL COMMENT '',
  `idtb_pedido` INT NOT NULL COMMENT '',
  `cantidad` VARCHAR(45) NULL COMMENT '',
  `subtotal` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idtb_producto`, `idtb_pedido`)  COMMENT '',
  INDEX `fk_tb_producto_has_tb_pedido_tb_pedido1_idx` (`idtb_pedido` ASC)  COMMENT '',
  INDEX `fk_tb_producto_has_tb_pedido_tb_producto1_idx` (`idtb_producto` ASC)  COMMENT '',
  CONSTRAINT `fk_tb_producto_has_tb_pedido_tb_producto1`
    FOREIGN KEY (`idtb_producto`)
    REFERENCES `db_bodeguitadeoro`.`tb_producto` (`idtb_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_producto_has_tb_pedido_tb_pedido1`
    FOREIGN KEY (`idtb_pedido`)
    REFERENCES `db_bodeguitadeoro`.`tb_pedido` (`idtb_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '					';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;









INSERT INTO `db_bodeguitadeoro`.`tb_tipo_persona` (`nombre`) VALUES ('cliente');
INSERT INTO `db_bodeguitadeoro`.`tb_tipo_persona` (`nombre`) VALUES ('administrador');



INSERT INTO `db_bodeguitadeoro`.`tb_persona` (`nombre`, `apellido`, `correo`, `clave`, `idtb_tipo_persona`) VALUES ('Brian', 'Peñaloza Ortega', '2013016328@unfv.edu.pe', '40bd001563085fc35165329ea1ff5c5ecbdbbeef', '1');
